name: Docker Image CI

on:
  push:
    branches: master

env:
  VERSION: v1.2.0-dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          - name: Build the latest Docker image
            run: docker build -t screetsec/sudomy:${VERSION} .
          - name: Push the latest Docker image
            run: docker push screetsec/sudomy:${VERSION}
